{% set name = "aiotube" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiotube-{{ version }}.tar.gz
  sha256: cf35fd58d84dc862f55fa48224a7465076893452deae37cf1c3ceaeb4f26d694

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pytube
    - urllib3
    - requests

test:
  imports:
    - aiotube
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jnsougata/AioTube
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: AioTube is a package created to power the user with YouTube Public Data functionality without YouTube Data API v3
  description: |
    All in one Tube is a package created to power the user with YouTube
    Data API functionality without API Key
  doc_url: https://github.com/jnsougata/AioTube
  dev_url: https://github.com/jnsougata/AioTube

extra:
  recipe-maintainers:
    - jan-janssen
